"use strict";

// Adapter for the sibling `whisk` module (All Sorted). It only runs when
// <ALLSORTED_ROOT>/whisk exists. The sibling spends on its own configured
// image provider; this adapter just calls its CLI and collects the file.

const fs = require("node:fs");
const { findSibling, adoptIntoLibrary } = require("./sibling");
const { BACKGROUND_SUFFIX, runProcess, sniffImage, short } = require("../util");
const { extractJson } = require("../../llm");

const LICENSE = "AI generated through your whisk module. Use is subject to the terms of the image provider configured there.";

function isConfigured({ env, fsImpl }) {
  const found = findSibling("whisk", ["src", "index.js"], { env, fsImpl });
  return { ok: found.ok, detail: found.detail };
}

async function generate({ prompt }, ctx) {
  const fsImpl = ctx.fsImpl || fs;
  const found = findSibling("whisk", ["src", "index.js"], { env: ctx.env, fsImpl });
  if (!found.ok) return { status: "not_configured", results: [], detail: found.detail };
  const run = ctx.runImpl || runProcess;
  fsImpl.mkdirSync(ctx.libraryDir, { recursive: true });
  const result = await run(process.execPath, [found.entry, "remix", "--text", `${prompt}. ${BACKGROUND_SUFFIX}`, "--json"], {
    timeoutMs: 180000,
    cwd: found.dir,
    env: { ...ctx.env, OUTPUT_DIRECTORY: ctx.libraryDir },
  });
  if (result.timedOut) return { status: "error", results: [], detail: "whisk timed out" };
  if (result.code !== 0) {
    const message = short(result.stderr || result.error || result.stdout, 200);
    const unconfigured = /provider key|unconfigured|not configured/i.test(message);
    return { status: unconfigured ? "not_configured" : "error", results: [], detail: `whisk: ${message || "failed"}` };
  }
  const parsed = extractJson(result.stdout);
  const produced = parsed && typeof parsed.filepath === "string" ? parsed.filepath : "";
  if (!produced) return { status: "error", results: [], detail: "whisk did not report an output file" };
  let file;
  try {
    if (!sniffImage(fsImpl.readFileSync(produced))) throw new Error("the output is not an image");
    file = adoptIntoLibrary(produced, { libraryDir: ctx.libraryDir, fsImpl });
  } catch (error) {
    return { status: "error", results: [], detail: `whisk: ${error.message}` };
  }
  const cost = parsed.cost != null ? `, cost reported: ${parsed.cost}` : "";
  return {
    status: "ok",
    detail: `generated by the whisk module${cost}`,
    results: [{ src: file, thumb: file, credit: "AI generated (whisk module)", license: LICENSE, alt: prompt }],
  };
}

module.exports = { id: "whisk", kind: "generate", env: ["ALLSORTED_ROOT"], license: LICENSE, isConfigured, generate };
